"""Knowledge base package: bundled GMP2010 regulation corpus.

- store.py     seed JSON loading + SQLite mirror (kb_entries, v8)
- retriever.py bigram-BM25 search + post-hoc finding enrichment (kb_refs)
- data/gmp2010.json  generated by scripts/seed_kb.py (committed; the source
  binary .doc is NOT tracked)
"""
from core.kb.retriever import attach_kb_refs, dedup_refs_for_report  # noqa: F401
from core.kb.store import ensure_db_seeded, entries, get_entry  # noqa: F401
