"""Knowledge base package: bundled multi-source regulation corpus.

- store.py     multi-source seed loading + SQLite mirror (kb_entries, v8)
- retriever.py bigram-BM25 search + post-hoc finding enrichment (kb_refs)
- data/raw/*.md     raw authoritative text + provenance header (committed)
- data/<id>.json    derived runtime payload, one per source (committed)

Sources are generated by scripts/seed_kb.py and committed, so end-user machines
never need Word COM. Every entry carries its own ``source_id``; each source has
its own content-hash version. ``source_meta()`` / ``entries()`` / ``chapters()``
default to the primary source for backward compatibility.
"""
from core.kb.retriever import (  # noqa: F401
    attach_kb_refs,
    dedup_refs_for_report,
    enabled_source_ids,
    group_refs_by_source,
)
from core.kb.store import (  # noqa: F401
    PRIMARY_SOURCE_ID,
    ensure_db_seeded,
    entries,
    get_entry,
    kb_version,
    source_ids,
    source_meta,
    sources,
)
