"""KB seed golden tests — core/kb/data/gmp2010.json structural invariants.

The JSON is generated by scripts/seed_kb.py from docs/2010版GMP.doc and is
committed to git. These tests lock its shape so a bad re-seed cannot silently
ship (GMP 引用数据的完整性直接影响 findings 依据可信度).
"""
import json
from pathlib import Path

DATA = Path(__file__).resolve().parents[2] / "core" / "kb" / "data" / "gmp2010.json"


def _payload() -> dict:
    return json.loads(DATA.read_text(encoding="utf-8"))


def test_seed_file_exists_and_shape():
    assert DATA.exists(), "seed JSON missing — run scripts/seed_kb.py"
    p = _payload()
    assert p["source_id"] == "gmp2010"
    assert "2010" in p["title"]


def test_chapter_count_is_14():
    ch = _payload()["chapters"]
    assert len(ch) == 14, f"GMP2010 正文共 14 章，实得 {len(ch)}"
    nos = [c["no"] for c in ch]
    assert nos == sorted(nos)
    assert nos[0] == 1 and nos[-1] == 14


def test_entry_count_and_ordering():
    en = _payload()["entries"]
    # GMP2010 正文 313 条；本 .doc 实际含 286 条独立条款（允许 ±6 解析方差）
    assert 280 <= len(en) <= 292
    nos = [e["no"] for e in en]
    assert nos == sorted(nos), "entries must be ascending by article no"
    ids = [e["entry_id"] for e in en]
    assert len(set(ids)) == len(ids), "duplicate entry_id"


def test_article_151_is_document_management():
    """第一百五十一条 = 文件管理操作规程条款 —— 检索相关性的锚点。"""
    en = _payload()["entries"]
    e151 = next(e for e in en if e["no"] == 151)
    assert "文件" in e151["text"]
    assert "规程" in e151["text"] or "管理" in e151["text"]


def test_no_degenerate_entries():
    en = _payload()["entries"]
    short = [e["entry_id"] for e in en if len(e["text"]) < 10]
    assert not short, f"degenerate entries: {short[:5]}"
    for e in en[:20]:
        assert e["article_label"].startswith("第") and \
            e["article_label"].endswith("条")
