"""KB seed golden tests — core/kb/data/gmp2010.json structural invariants.

The JSON is generated by scripts/seed_kb.py from docs/2010版GMP.doc and is
committed to git. These tests lock its shape so a bad re-seed cannot silently
ship (GMP 引用数据的完整性直接影响 findings 依据可信度).
"""
import json
from pathlib import Path

DATA = Path(__file__).resolve().parents[2] / "core" / "kb" / "data" / "gmp2010.json"


def _payload() -> dict:
    return json.loads(DATA.read_text(encoding="utf-8"))


def test_seed_file_exists_and_shape():
    assert DATA.exists(), "seed JSON missing — run scripts/seed_kb.py"
    p = _payload()
    assert p["source_id"] == "gmp2010"
    assert "2010" in p["title"]


def test_chapter_count_is_14():
    ch = _payload()["chapters"]
    assert len(ch) == 14, f"GMP2010 正文共 14 章，实得 {len(ch)}"
    nos = [c["no"] for c in ch]
    assert nos == sorted(nos)
    assert nos[0] == 1 and nos[-1] == 14


def test_entry_count_and_ordering():
    en = _payload()["entries"]
    # GMP2010 正文共 313 条 —— 与官方文本条数一致，精确锁定（不再允许方差）。
    assert len(en) == 313, f"GMP2010 正文应为 313 条，实得 {len(en)}"
    nos = [e["no"] for e in en]
    assert nos == sorted(nos), "entries must be ascending by article no"
    ids = [e["entry_id"] for e in en]
    assert len(set(ids)) == len(ids), "duplicate entry_id"


def test_article_numbers_are_contiguous():
    """条号必须 1..313 连续。

    回归：早期 ``_ARTICLE_RE`` 的字符类漏了『零』，编码含零的条文
    （第一百零一~一百零九 / 二百零一~二百零九 / 三百零一~三百零九，共 27 条）
    从未被切分，正文被静默并入前一条 —— 这些条款既无法引用，前一条正文也被
    污染。此测试锁定该缺陷不再复发。
    """
    nos = [e["no"] for e in _payload()["entries"]]
    assert nos == list(range(1, 314)), (
        "条号必须连续 1..313；缺号通常意味着中文数字正则又漏了字符"
    )


def test_zero_numbered_articles_exist_and_are_clean():
    """含『零』的条文（如第二百零一条 清场记录）必须独立成条且正文干净。"""
    en = {e["no"]: e for e in _payload()["entries"]}
    e201 = en[201]
    assert e201["article_label"] == "第二百零一条"
    assert "清场记录" in e201["text"]
    # 前一条不得再吞并后一条的正文
    assert "第二百零一条" not in en[200]["text"], "第二百条正文被第二百零一条污染"


def test_article_151_is_document_management():
    """第一百五十一条 = 文件管理操作规程条款 —— 检索相关性的锚点。"""
    en = _payload()["entries"]
    e151 = next(e for e in en if e["no"] == 151)
    assert "文件" in e151["text"]
    assert "规程" in e151["text"] or "管理" in e151["text"]


def test_no_degenerate_entries():
    en = _payload()["entries"]
    short = [e["entry_id"] for e in en if len(e["text"]) < 10]
    assert not short, f"degenerate entries: {short[:5]}"
    for e in en[:20]:
        assert e["article_label"].startswith("第") and \
            e["article_label"].endswith("条")
